name: booking
description: A hotel booking demo app.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  logger: ^2.0.2
  json_annotation: ^4.8.1
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.5

dev_dependencies:
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0' 
  json_serializable: ^6.6.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.otf
          weight: 300
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.otf
          weight: 400
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLD.otf
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYBOLD.otf
          weight: 600
  generate: true
